### PR TITLE
Performance

### PR DESCRIPTION
**Pull request by mmahalwy**
Fies #122

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32791

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32793

**Comment by mmahalwy** [comment]
Down to
```
 [Info]   Completed 200 OK in 928ms (Views: 849.7ms | ActiveRecord: 71.2ms)
```

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32794

**Comment by mmahalwy** [comment]
Ok this is good on my end

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32795

**Pull request merged**
