### PR TITLE
Es and remove v2

### PR DESCRIPTION
**Pull request by naveed-ahmad**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32784

**Comment by mmahalwy** [comment]
Don't need this file for now `db/data source/Transliteration.csv`
I don't think we will go down that for now.

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32790

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32791

**Pull request merged**
