### PR TITLE
improved search and navigational results

### PR DESCRIPTION
**Pull request by naveed-ahmad**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32854

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32855

**Comment by mujahid515** [comment]
https://api.quran.com/api/v4/search?q=musa
https://api.quran.com/api/v3/search?q=musa

V3 and V4 of this API returns the following:

{
"status": 500,
"error": "Internal Server Error"
}

It was working for the past week and then suddenly stopped working yesterday. I presume this merge has something to do with it. Any idea when this will be fixed?

**Comment by ahmedre** [comment]
i've rolled back the deployment for now while @naveed-ahmad can look into this.

**Pull request merged**
