### PR TITLE
Save build artifacts and generate sitemaps

### PR DESCRIPTION
**Pull request by hammady**
To build, just run `./build.sh`. For other env (production or test), just run: `RAILS_ENV=production ./build.sh`.
This caches build artifacts (gems) so that subsequent builds are faster. This behavior is only supported in development. For production, bundle adds `--deployment` and `--clean` which are not cache friendly.
One more important thing is that this build copies `Gemfile.lock` back from the built image to the host so that it can be checked into source control after successful builds that adds/removes gems.

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32855

**Comment by mmahalwy** [comment]
cc @naveed-ahmad

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32916

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32919

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32920

**Comment by hammady** [comment]
Now includes 9e0d9415e929e889a14ee81f297082e1400fb452 to generate sitemaps on `docker run`

**Pull request merged**
