### PR TITLE
added sitemap

### PR DESCRIPTION
**Pull request by naveed-ahmad**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32913

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32914

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32915

**Comment by hammady** [comment]
@naveed-ahmad please reopen, Dockerfile misses `rake` after `bundle exec`, build fails.

**Comment by hammady** [comment]
Actually, after trying this, it looks like `Dockerfile` is not the correct place for running such rake tasks. The reason is that it requires the whole rails stack to be up which is not the case when invoking `docker build`. In my case, it was complaining that the database is not there. Skipping database is not an option, because sitemap generation itself relies on the database. 
I removed the rake task from the Dockerfile RUN and moved it to CMD. More details in #171

**Pull request merged**
