### PR TITLE
added tafsir endpoint

### PR DESCRIPTION
**Pull request by naveed-ahmad**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32777

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32778

**Comment by mmahalwy** [comment]
Sorry man, I feel like this PR needs a tiny bit more work. You have written some magic before!

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32784

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32785

**Comment by naveed-ahmad** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32787

**Comment by ahmedre** [comment]
Deployed to: http://staging.quran.com:32795

**Pull request merged**
